Feature/expire
VeliovGroup/Client-Storage pull request #5
Opened 2019-04-28 19:23 UTC by hakod

Hi @dr-dimitru,

I added an expiration feature for while code is still active. Wasn't sure whether to add timestamp for expiration date since the other PR already had that. Please let me know if I should change it to use a timestamp as well. Thanks again.

2019-04-28 19:57 UTC, dr-dimitru commented
@hakod thank you for the quick PR.

 1. How is it going to work after page reload?
 2. Yes, don't mind another PRs
 2. Please let's discuss an idea before implementing it

2019-04-28 20:39 UTC, hakod commented
@dr-dimitru No problem! Yeah, I was concerned that the setTimeout would be interrupted. Would a timestamp be the best route and should there be a setInterval to check for expiration every so often? Thanks for reviewing.

2019-04-28 22:32 UTC, dr-dimitru commented
@hakod I believe we should utilize cookie's expiration in case if cookies are used, use records with `.___expireAt` prefix holding expirations timestamp, having loop via `setInterval(()=>{}, 256)` for LocalStorage, and use `setTimeout` for JS implementation when LocalStorage nor Cookies are available. Does it sounds clear?

2019-04-28 23:52 UTC, hakod commented
@dr-dimitru Yes, I think I understand it.

2019-04-29 03:02 UTC, hakod commented
@dr-dimitru Added the cookie expiration using max-age and the prefix to store expiration times. Let me know if there are any changes needed. Thanks.

2019-04-29 03:04 UTC, dr-dimitru requested changes

2019-04-29 03:04 UTC, dr-dimitru commented on client-storage.js
> +      document.cookie = key + "=" + value + "; max-age=" + seconds + "; path=/";
Please use `this.cookies` [library](https://github.com/VeliovGroup/Client-Storage/blob/master/client-storage.js#L78) here. You can update `this.cookies.set` method to support expiration date

2019-04-29 03:04 UTC, dr-dimitru commented on client-storage.js
> +    return true
I'd use `else if` here

2019-04-29 03:04 UTC, dr-dimitru commented on client-storage.js
> +      if (key.slice(-11) === "._expiredAt") {
I'd use ES6 `.includes('._expiredAt')` method and single quotes on the strings

2019-04-29 03:04 UTC, dr-dimitru commented on client-storage.js
> +LSExpire();
Only if `localStorage` is used

2019-04-29 03:04 UTC, dr-dimitru commented on client-storage.js
> +LSExpire();
Should be in constructor

2019-04-29 03:04 UTC, dr-dimitru commented
@hakod thank you, added notes

2019-04-30 05:35 UTC, hakod commented
@dr-dimitru Thanks for the feedback, I really appreciate it. The last note was a bit difficult for me to fix. Should setInterval be triggered whenever page loads? How could I get that working?

2019-04-30 06:01 UTC, dr-dimitru requested changes
Check inside constructor if `localStorage` is supported and `setInterval`

2019-04-30 06:01 UTC, dr-dimitru commented on client-storage.js
> +    case 'localStorage':
Please, no indentation inside `switch(){}`

2019-05-01 04:58 UTC, hakod commented
@dr-dimitru OK, I think I got it. Let me know, thanks.

2019-05-22 08:51 UTC, dr-dimitru commented
Dear @hakod ,

Thank you for your PR and attempt, final solution released as [`v3.0.0`](https://github.com/VeliovGroup/Client-Storage/releases/tag/3.0.0).
Do not hesitate to share your opinion 👨‍💻

2019-05-22 08:51 UTC, closed without merging

2019-06-28 02:02 UTC, hakod commented
Hi @dr-dimitru, 
It is interesting you used a while statement instead of setInterval to remove localstorage. Wondering what the reason for that change was.

2019-06-28 07:14 UTC, dr-dimitru commented
@hakod not using `while` nor `setInterval`. Timers are unreliable in Browser's runtime environment. Timers will also pollute JS runtime. So, I'm just checking for expiration date [here](https://github.com/VeliovGroup/Client-Storage/blob/master/client-storage.js#L243) and remove it from storage if expired, it's also happening when *ClientStorage* instance is initiated

2019-06-28 21:03 UTC, hakod commented
OK I think I understand it now. Would it delete without a page refresh too?

2019-06-28 21:07 UTC, dr-dimitru commented
No, only upon request if expired or on page init. Very similar to how cookies and expiration works in most of browsers

2019-06-29 01:56 UTC, hakod commented
That makes a lot more sense. Thanks.